### ISSUE TITLE
TeX-AMS_HTML configuration + [EXPECTED ERROR] while trying to render math on the page

### ISSUE THREAD

**Issue by drochgenius** [pkra/MathJax-single-file#14] opened 2017-04-27 13:59 UTC
Hi @pkra ,

Thanks for providing this example on how we can bundle mathjax in a single file.

When I use the files in the `dist` folder, it works, but somehow what I rebuild them with `grunt` it doesn't.

I get `[EXPECTED ERROR]` on the page, and nothing in the logs.

Basically, I'd like to build a bundle with **TeX-AMS_HTML** configuration, but I'm not sure where to get the list of required files and extensions, in the proper order. I would appreciate if you could give me some quick guidance on how to approach this.

Of course, if I can build this bundle, I'm happy to contribute the script back to this repo.

Thanks in advance,

Dominique

**Comment by drochgenius** [comment] 2017-04-27 14:05
Actually, I just found that I'm missing a good half of the file content after bundling.
Investigating

**Comment by pkra** [comment] 2017-04-27 14:48
The HTML outputs should be very different since they use fonts. I have never had time to look into it in detail, to be honest.

First, I would suggest to look at the CommonHTML output since that doesn't require the webfont-loading hacks that the HTML-CSS output needs.

You won't need any of the `unpacked/jax/output/SVG/fonts/TeX/*` files because that's the SVG equivalent of the webfonts (which CommonHTML will simply load via CSS).

Maybe you can share something by PR?

**Comment by pkra** [comment] 2017-04-27 15:36
I've pushed a non-working version to https://github.com/pkra/MathJax-single-file/tree/texhtml for first steps. Will have to check into the remaining issue some other time.

**Comment by drochgenius** [comment] 2017-04-27 16:19
Thanks a lot for this @pkra ,  you give me a starting point, and that's greatly appreciated!

I have resolved my initial issue about `[EXPECTED ERROR]`, and I've open a pull request for you to review.

I will start looking into the `texhtml` non-working version.
Not sure to understand the issue you mentioned above, let me look into it.

Thanks for the prompt response,

Dominique

**Comment by drochgenius** [comment] 2017-04-27 18:34
HI again @pkra ,

I checked out your branch, and tried the non-working `texhtml` build.
It's not clear to me what the font issue is, and I'd like to troubleshoot?
I have no idea how to approach debugging on MathJax, is there a way to turn on debug logs of some sort? 
The only thing I see is that math is not rendering on screen, but the MathJaX object is ready.

Any insight would be greatly appreciated!

Thanks

**Comment by pkra** [comment] 2017-04-27 19:29
Thanks for checking it out. One problem with the single-file builds is that they hack too much, making debugging harder. I will try to dig deeper tomorrow and check with our lead developer.

**Comment by pkra** [comment] 2017-04-28 13:36
I think I figured out my mistake.

```
unpacked/jax/output/CommonHTML/fonts/TeX/fontdata.js
unpacked/jax/output/CommonHTML/fonts/TeX/fontdata-extra.js
```

need to be moved to an earlier point (cf the SVG fontdata files).

I'll confirm later and push an update.

**Comment by pkra** [comment] 2017-04-28 13:38
Oh, and the webfont URL probably needs some custom handling (I have locally installed fonts)

**Comment by drochgenius** [comment] 2017-04-28 15:04
Hi @pkra ,

I really appreciate you're looking into this.

So I understand the issue is related to the font data.

I think it's OK to have the fonts locally, and if we could customize the path from where to load the fonts in Mathjax, through configuration for example, that would be great.

I am looking forward to your update,

Regards

Dominique

**Comment by pkra** [comment] 2017-04-28 15:20
> I think it's OK to have the fonts locally, and if we could customize the path from where to load the fonts in Mathjax, through configuration for example, that would be great.

It's not a real problem to provide webfonts; basically a config option. I just wrote this here so I don't forget it :smile_cat:

**Comment by pkra** [comment] 2017-04-28 15:36
FYI I pushed the small change to the `texhtml` branch. Will look more later.

**Comment by drochgenius** [comment] 2017-04-30 17:22
Hi @pkra ,

I have a quick question. What's the difference between CHTML and HTML configs, that make it much more complicated to bundle?
Is it the CSS?

In the documentation you say that MathJax is composed of different things not just Javascript.
So you probably have fonts and css, maybe image assets, anything else I should be aware of?

I think it's probably reasonable to add a configuration option for assets paths/url.

Regards

**Comment by pkra** [comment] 2017-05-02 07:53
> What's the difference between CHTML and HTML configs, that make it much more complicated to bundle?

If you are referring to [my comment above](https://github.com/pkra/MathJax-single-file/issues/14#issuecomment-297735767), then I was simply wrong. I had expected it to be more complicated. 

> In the documentation you say that MathJax is composed of different things not just Javascript.
So you probably have fonts and css, maybe image assets, anything else I should be aware of?

Only fonts (in the `fonts` folder of MathJax). CSS is generated on the fly.

> I think it's probably reasonable to add a configuration option for assets paths/url.

If you mean here, then you can simply change the URL in `html-helper-fonturl`.

If you mean, on a site, you can use the same call that the `html-helper-fonturl.js` uses (customized as necessary) in a regular MathJax configuration (as usual before loading MathJax itself).

**Comment by drochgenius** [comment] 2017-05-02 17:23
Thanks a lot for this @pkra,
This is very good news.
I will review in the coming days, and close out this issue.

Regards

**Comment by drochgenius** [comment] 2017-05-08 17:20
Hi @pkra ,

There is something strange I have noticed using the new single file CHTML MathJax. When I look at the generated HTML markup, it's different than what is generated using the CDN. Would you be able to through some light on this?

Here is the configuration I use with the CDN:

```javascript
self.MathJax.Hub.Config({
    'HTML-CSS': {
        fonts: ['Latin-Modern'],
    },
    TeX: {
        extensions: ['enclose.js', 'cancel.js', 'HTML.js'],
    },
    tex2jax: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        processEscapes: true,
    },
    messageStyle: 'none',
});
```
**BEFORE**
![typesetting-before](https://cloud.githubusercontent.com/assets/12520749/25816348/d81a54be-33f1-11e7-9dbb-5e6f3fb761da.png)

![mathjax-markup-before](https://cloud.githubusercontent.com/assets/12520749/25816066/dc19046c-33f0-11e7-95bb-c063f85e1221.png)

**AFTER**
![typesetting-after](https://cloud.githubusercontent.com/assets/12520749/25816386/f3f7dfa8-33f1-11e7-80bf-9f4e049e604b.png)


![mathjax-matkup-after](https://cloud.githubusercontent.com/assets/12520749/25816067/dc1a54ca-33f0-11e7-8021-202ac28469cd.png)

More importantly, the typesetting quality is not as good.

Thanks for clarifying,
Regards,

Dominique

**Comment by pkra** [comment] 2017-05-09 07:02
You are using the HTML-CSS output and Latin-Modern fonts. The file I built uses the CommonHTML output (which only supports the default fonts right now).

Since the HTML-CSS output will be dropped in v3, I wasn't planning on spending time on it. But it shouldn't be much different if you want to give it a try.

**Comment by drochgenius** [comment] 2017-05-09 12:55
Thanks @pkra ,

I didn't know HTML-CSS was deprecated.
What do you mean exactly by CommonHTML? Is this Compact HTML (https://en.wikipedia.org/wiki/C-HTML) ? What is the difference between the two? 

I'm happy to use the CHTML configuration if it's the one that you'll be supporting.
The only thing that disappoint me is the rendering is not as beautiful as it used to, which is a major reason why I've decided to use MathJax in the first place.

Well, OK I understand it has to do with the font support, which is a whole subject on its own.
I had already reached out to you a couple of months ago on how to use custom fonts in MathJax. Based on the complexity, we'd decided to use Latin Modern font which is satisfying for the moment. 

In the meantime, I'll try to setup an HTML configuration and see if I am able to get this working.

Regards

**Comment by pkra** [comment] 2017-05-09 12:56
> What do you mean exactly by CommonHTML?

That's the name of one of our output components, cf. http://docs.mathjax.org/en/latest/output.html#mathjax-output-components

**Comment by drochgenius** [comment] 2017-05-09 13:18
Thanks for this link, I'll read through carefully.

**Comment by pkra** [comment] 2017-05-10 07:01
Time for a longer reply.

> I didn't know HTML-CSS was deprecated.

It is not in 2.x. But it cannot fit into the architecture of v3 as it is highly client-specific and is extremely hacky in its layout (it was designed for a world where IE8 was brand new).

> The only thing that disappoint me is the rendering is not as beautiful as it used to

We'd like to hear more about that but please file bug reports at the core repo.

> Well, OK I understand it has to do with the font support, which is a whole subject on its own.

No, that's just a current limitation of the CommonHTML output. It will support all our fonts in v3.

> I had already reached out to you a couple of months ago on how to use custom fonts in MathJax

That will also get easier in v3.

**Comment by drochgenius** [comment] 2017-05-10 12:39
Thanks @pkra  for taking the time to give me more details on this.

I am looking forward to v3, especially for better font flexibility.
In the meantime, I'll try to setup an HTML-CSS config in the grunt file staring with the CommonHTML you've just implemented.

I will file an issue with more details on the display issues I've noticed with CommonHTML so it can be fixed during v3 development.

I suppose you are keeping a backlog for v3?
I am open to take on some of these items.

Regards

**Comment by pkra** [comment] 2017-05-15 16:32
@drochgenius in case you missed it, I've started a re-write #19. Would be interested in input.

**Comment by pkra** [comment] 2017-05-29 08:54
Closing this for now.

**Closed as completed by pkra** 2017-05-29 08:54 UTC
